
version: 2

models:
  - name: customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: odd_customer
    description: "Customers that have an odd account balance"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null